### ISSUE TITLE
rugged segmentation fault

### ISSUE THREAD

**Issue by gdubicki** [adrienthebo/r10k#1280]
## Describe the Bug

I am getting a segmentation fault when trying to use rugged provider:
```
WARN     -> "basedir" is deprecated. Please use "environment_name" instead. "basedir" will be removed in a future version.
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/r10k-3.14.2/lib/r10k/git/rugged/working_repository.rb:143: [BUG] Segmentation fault at 0x0000000000000000
```
Full output: https://pastebin.com/n6u8JLuQ

## Expected Behavior

Rugged provider should work.

## Steps to Reproduce

I have used cmake3 package so I can install the latest rugged, 1.1.0. As prerequisites I installed 'libssh2-devel', 'openssl', 'openssl-devel' in their latest versions. Rugged can be loaded and shows the right features:
```
# /opt/puppetlabs/puppet/bin/irb
irb(main):001:0> require('rugged')
=> true
irb(main):002:0> Rugged.features
=> [:threads, :https, :ssh]
```

My r10k.yaml:
```
---
cachedir: '/etc/puppetlabs/code/r10k-cache'
git:
  provider: 'rugged'
  private_key: '/root/.ssh/id_rsa'
sources:
  envs:
    remote: git@git.company.com:sddc/envs.git
    basedir: /etc/puppetlabs/code/environments
```

## Environment

- Version: 3.14.2
- Platform: Centos 7, Puppet 5.5.22
